name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]  # ou "master", se for esse o nome do seu branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Rodar testes
        run: |
          pip install -r requirements.txt
          python -m unittest discover

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy para o Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "NOME-DO-SEU-APP-HEROKU"
          heroku_email: "SEU-EMAIL@EXEMPLO.COM"
