name: CI/CD Pipeline  # Nome da sua pipeline (pode deixar assim mesmo)

on:
  push:
    branches: [ "main" ]  # Altere para "master" se o nome do seu branch principal for diferente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Voc칡 pode mudar a vers칚o do Python se estiver usando outra

      - name: Instalar depend칡ncias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Garante que todas as libs necess치rias sejam instaladas

  test:
    runs-on: ubuntu-latest
    needs: build  # S칩 executa os testes se o build funcionar
    steps:
      - uses: actions/checkout@v3
      - name: Rodar testes
        run: |
          pip install -r requirements.txt
          python -m unittest discover  # Comando que roda seus testes do arquivo test_app.py

  deploy:
    runs-on: ubuntu-latest
    needs: test  # S칩 faz o deploy se os testes passarem
    steps:
      - name: Deploy para o Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}  # Essa vari치vel voc칡 cria no GitHub (Settings > Secrets > Actions)
          heroku_app_name: "SEU-NOME-DO-APP-NO-HEROKU"    # 游대 ALTERE AQUI para o nome do seu app no Heroku
          heroku_email: "SEU-EMAIL@EXEMPLO.COM"          # 游대 ALTERE AQUI para o e-mail da sua conta do Heroku
